---
name: Validate GitHub Workflows
on:
  workflow_call:
    inputs:
      workflows-path:
        description: "The path to the GitHub workflows"
        required: false
        type: string
        default: ".github/workflows"

jobs:
  validate-workflows:
    name: Validate GitHub Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: 1.25.x
          cache: true
      - name: Install Actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - name: Run Actionlint
        id: actionlint
        run: actionlint ${{ inputs.workflows-path }}/*.yml
